language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
services: 
  - mongodb
  - redis-server
before_script:
  - echo 'extension="mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update || true
script: ./build.php
